/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_victorvalladares;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;


/**
 *
 * @author valla
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        planetasBase();
        cargarCientificos();
        actualizarCB();
    }

    public void planetasBase(){
        Terrestre mercurio = new Terrestre ("Mercurio",5000,13000,400,300);
        planetas.add(mercurio);
        Terrestre venus = new Terrestre ("Venus",100000,15000,640,260);
        planetas.add(venus);
        Terrestre tierra = new Terrestre ("Tierra",140000,17000,760,570);
        planetas.add(tierra);
        Terrestre marte = new Terrestre ("Marte",90000,12000,360,360);
        planetas.add(marte);
        Gaseoso jupiter = new Gaseoso ("Jupiter",400000,40000,340,310);
        planetas.add(jupiter);
        Gaseoso saturno = new Gaseoso ("Saturno",300000,30000,560,450);
        planetas.add(saturno);
        Gaseoso urano = new Gaseoso ("Urano",200000,20000,670,690);
        planetas.add(urano);
        Gaseoso neptuno = new Gaseoso ("Neptuno",200000,20000,840,900);
        planetas.add(neptuno);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_up = new javax.swing.JPopupMenu();
        item_planeta1 = new javax.swing.JMenuItem();
        item_planeta2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        pgr_tiempo = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_planetas = new javax.swing.JTree();
        bt_colisionar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        label_p1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        label_p2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_cientifico = new javax.swing.JComboBox<>();
        ch_publicos = new javax.swing.JCheckBox();
        tf_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bt_crear = new javax.swing.JButton();

        item_planeta1.setText("Planeta 1");
        item_planeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_planeta1ActionPerformed(evt);
            }
        });
        pop_up.add(item_planeta1);

        item_planeta2.setText("Planeta 2");
        item_planeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_planeta2ActionPerformed(evt);
            }
        });
        pop_up.add(item_planeta2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pgr_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 40));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Planetas");
        jt_planetas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_planetas.setComponentPopupMenu(pop_up);
        jScrollPane1.setViewportView(jt_planetas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 300));

        bt_colisionar.setText("Colisionar");
        bt_colisionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colisionarMouseClicked(evt);
            }
        });
        jPanel1.add(bt_colisionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 120, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 200, 20));
        jPanel1.add(label_p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 40));

        jLabel2.setText("Planeta 2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, 20));
        jPanel1.add(label_p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, 40));

        jLabel4.setText("Planeta 1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        cb_cientifico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_cientificoItemStateChanged(evt);
            }
        });
        jPanel1.add(cb_cientifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 200, 30));

        ch_publicos.setText("Publicos");
        ch_publicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch_publicosItemStateChanged(evt);
            }
        });
        jPanel1.add(ch_publicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));
        jPanel1.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 200, -1));

        jLabel5.setText("Cientifico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        bt_crear.setText("Crear Cientifico");
        bt_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearMouseClicked(evt);
            }
        });
        jPanel1.add(bt_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearMouseClicked
        if (tf_nombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No ha puesto un nombre para el cientifico");
        }else{
            String nombre = tf_nombre.getText();
            Cientifico cientifico = new Cientifico(nombre);
            cientificos.add(cientifico);
            JOptionPane.showMessageDialog(null, "Se ha creado el cientifico");
            tf_nombre.setText(null);
            actualizarCB();
            guardarCientifico();
        }
    }//GEN-LAST:event_bt_crearMouseClicked

    private void ch_publicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch_publicosItemStateChanged
        if (ch_publicos.isSelected()){
            publicoArbol();
            
        }
    }//GEN-LAST:event_ch_publicosItemStateChanged

    private void cb_cientificoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_cientificoItemStateChanged
        if(evt.getStateChange() == 2){
            cientificoArbol();
        }
        if (ch_publicos.isSelected()){
            ch_publicos.setSelected(false);
        }
    }//GEN-LAST:event_cb_cientificoItemStateChanged

    private void item_planeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_planeta1ActionPerformed
        try{
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode)jt_planetas.getLastSelectedPathComponent();
            planeta1 = (Planeta)selectedNode.getUserObject();
            label_p1.setText(planeta1.toString());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
    }//GEN-LAST:event_item_planeta1ActionPerformed

    private void item_planeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_planeta2ActionPerformed
        try{
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode)jt_planetas.getLastSelectedPathComponent();
            planeta2 = (Planeta)selectedNode.getUserObject();
            label_p2.setText(planeta2.toString());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
    }//GEN-LAST:event_item_planeta2ActionPerformed

    private void bt_colisionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colisionarMouseClicked
        if(planeta1 == null || planeta2 == null){
            JOptionPane.showMessageDialog(null, "No hay planetas para colisionar");
        }else{
            try{
                double distanciax = Math.pow(planeta1.getX() - planeta2.getX(), 2); 
                double distanciay = Math.pow(planeta1.getY() - planeta2.getY(), 2);
                double total = distanciax + distanciay;
                double distancia = Math.sqrt(total);
                int distancia1 = (int) Math.round(distancia);
                pgr_tiempo.setMaximum(distancia1); 
                Cientifico cientifico = (Cientifico) cb_cientifico.getSelectedItem();
                hilo = new HiloProgressBar(pgr_tiempo, planeta1, planeta2, cientifico);
                hilo.start();
                guardarCientifico();
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        }
        
    }//GEN-LAST:event_bt_colisionarMouseClicked

    public void actualizarCB(){
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_cientifico.getModel();
        modelo.removeAllElements();
        for (Cientifico c : cientificos)
            modelo.addElement(c);
    }
    
    public void publicoArbol(){
        DefaultTreeModel modelo = (DefaultTreeModel)jt_planetas.getModel();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Planetas");
        for (Planeta planeta : planetas){
            DefaultMutableTreeNode hojaPlaneta = new DefaultMutableTreeNode(planeta);
            root.add(hojaPlaneta);
        }
        modelo.setRoot(root);
    }
    
    public void cientificoArbol(){
        try{
            Cientifico cientifico = (Cientifico) cb_cientifico.getSelectedItem();

            DefaultTreeModel modelo = (DefaultTreeModel)jt_planetas.getModel();
            DefaultMutableTreeNode root = new DefaultMutableTreeNode("Planetas");
            root.removeAllChildren();
            for (Planeta planeta : cientifico.getPlanetas()){
                DefaultMutableTreeNode hojaPlaneta = new DefaultMutableTreeNode(planeta);
                root.add(hojaPlaneta);
            }

            modelo.setRoot(root);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: El cientifico no tiene planetas");
        }
    }
    
    private void guardarCientifico(){
        try{
            ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("./cientificos"));
            for (Cientifico cientifico : cientificos)
                os.writeObject(cientifico);
        }catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
    }
    
    private void cargarCientificos(){
        try{
            ObjectInputStream os = new ObjectInputStream(new FileInputStream("./cientificos"));
            Cientifico cientifico;
            while( (cientifico = (Cientifico)os.readObject()) != null )
                cientificos.add(cientifico);
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_colisionar;
    private javax.swing.JButton bt_crear;
    private javax.swing.JComboBox<String> cb_cientifico;
    private javax.swing.JCheckBox ch_publicos;
    private javax.swing.JMenuItem item_planeta1;
    private javax.swing.JMenuItem item_planeta2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTree jt_planetas;
    private javax.swing.JLabel label_p1;
    private javax.swing.JLabel label_p2;
    private javax.swing.JProgressBar pgr_tiempo;
    private javax.swing.JPopupMenu pop_up;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
    ArrayList <Cientifico> cientificos = new ArrayList ();
    ArrayList <Planeta> planetas = new ArrayList ();
    Planeta planeta1;
    Planeta planeta2;
    HiloProgressBar hilo;
}
